name: SBan
version: 1.0
main: com.shadow5353.SBan
description: Make notes on players for other staff members

commands:
    tempban:
        usage: /<command>
        description: Main Command
        aliases: [ban, sban]
